hash-format = "sha256"

[[files]]
file = "bin/version.json"
hash = "517d3dcd1f6c9c51268f208356c3443a4941cb03827b80db8754ee067484852a"

[[files]]
file = "config/arcanus.json5"
hash = "0ca72244069750b2b7dbf6ce19439db81a83b6210e86dbff3ef68ac03c4b5f2d"

[[files]]
file = "config/campanion.json"
hash = "4fdaba16469ef05113c60d6d0aee2eb52371d53f41b29cafc3635706459fb6c1"

[[files]]
file = "config/customsplashscreen.json5"
hash = "c5fc25ecbdd4262532a449163db31eddb5fc5aba5cbeea1ba49f31808fce5219"

[[files]]
file = "config/customsplashscreen/background.jpg"
hash = "1f2f9083e336a23f21776e31abc666a0c1fe867529522015fdf6f578b3e38dfc"

[[files]]
file = "config/customsplashscreen/hexmc.png"
hash = "1067701209c439e82ddf4e2bd413f7198aacb3cb3016e924ada41550914a5745"

[[files]]
file = "config/customsplashscreen/logo.png"
hash = "7e4897e9f11f9c44aaafdf6c5890803ff5e2908806748f89f1ac596e4e612f42"

[[files]]
file = "config/customsplashscreen/mojangstudios.png"
hash = "27b2ea2946ca5b00841ce7d1813b42dfb7e36b12ad50c7c9bea09053ac226cf3"

[[files]]
file = "config/customsplashscreen/progressbar.png"
hash = "e2e0555e30fd677e05570551f36d3a95fd844dcadc62b15e4f901c3442a5e3c7"

[[files]]
file = "config/customsplashscreen/progressbar_background.png"
hash = "6e2fa0adee9638b3e8f36e75ad048f0abb0de2d06b591961c6b2aff943fd46f2"

[[files]]
file = "config/desiredServers/desiredservers.json"
hash = "08329c92e6096df70462cfd23aa746067051669ccc37b1b0ef76363266e1e314"

[[files]]
file = "config/yosbr/config/MiniMOTD/icons/HexMC64.png"
hash = "6e54be89cf100d8c8bfe6769c6f9d60ab8d9fb78c3092b7f11a04c9423d0667c"

[[files]]
file = "config/yosbr/config/MiniMOTD/main.conf"
hash = "418b145db2cf2946af812c8119de682e6caf568ba5c389eeb2d17247bee94933"

[[files]]
file = "config/yosbr/config/MiniMOTD/plugin_settings.conf"
hash = "fe88437fdd58b33029c24ed621a232733bad49f8bf48b1cbb80e0a4a25f46bdc"

[[files]]
file = "config/yosbr/config/bobby.conf"
hash = "7668a9ed5d5d6878dd49d552396b7aab57e5345d031a0f776b90f9a477a06195"

[[files]]
file = "config/yosbr/config/borderlessmining.json"
hash = "1dfdc3360afe91b5804eef79f8b868f874e3dfc0c975495f8994f378ffe37a8f"

[[files]]
file = "config/yosbr/config/capes.json5"
hash = "8f5c4bac35757d624f296419976aff70a4a5b95c4430aff06048013ea7dd25c4"

[[files]]
file = "config/yosbr/config/debugify.json"
hash = "e42d605709dbede0b7db4b3392a12c851d572398af021e285e02e3499bca8b7b"

[[files]]
file = "config/yosbr/config/dynamicfps.toml"
hash = "00adc4f855ed41412f3c3eb48b859c4ae68b5f2c30ba4c332e66f38e79a0c449"

[[files]]
file = "config/yosbr/config/iris.properties"
hash = "1786a6b8a60d295944e28a4585ba7f9a2f4d2c58bbe5e1932675e27b6f11f3e8"

[[files]]
file = "config/yosbr/config/lambdabettergrass.toml"
hash = "a96351b4d852862f0c994cd61a05856c965e73e8f698591f0f2f5ba9a30bd952"

[[files]]
file = "config/yosbr/config/lambdynlights.toml"
hash = "5b83dbf79c2df634529371bb6fe139fadaf485710212080363a522f2f5983ca6"

[[files]]
file = "config/yosbr/config/servercore.toml"
hash = "df19e2800d1be4d4eb6a30c63ba0aa3e4c0b2e1f2174c5ffcc50418a8b437180"

[[files]]
file = "config/yosbr/config/sodium-extra-options.json"
hash = "4d20619bd1cab384de10738a95ca6943be094bb5df21dc630d3400f25450a03e"

[[files]]
file = "config/yosbr/config/sodium-options.json"
hash = "dd6f94bc9b0002d8db083a1f7a4238fd93489046f3084b03ce92338ab5a65b00"

[[files]]
file = "config/yosbr/options.txt"
hash = "34a2111b33b0c63e7d48e874c6e9c7536d57c050d6c8302e941e1a58c6db1fca"

[[files]]
file = "mods/RoughlyEnoughItems-8.1.457.jar"
hash = "1702f409482e607f68512303e522ad34ea6c31d4d149fc28983343cf62602e4e"

[[files]]
file = "mods/TerraBlender-fabric-1.18.2-1.1.0.99.jar"
hash = "acbff3e5c672c3725194a0536c809e4d5814467bb6eec18bf2ec9feef428ae36"

[[files]]
file = "mods/addadd.toml"
hash = "817d444340345cbd5eb9860d1fd2eccabfc54e5579c5f46d05e05e150573c769"
metafile = true

[[files]]
file = "mods/adorn.toml"
hash = "5e5cd9403870724d633b352ebec5a0440eb1d5369feec48378b844e2179c4000"
metafile = true

[[files]]
file = "mods/advancementinfo.toml"
hash = "46de5114d8a0017b14c0f6b63401fc7a1cb69b0dce336d36e25e80e91b51319b"
metafile = true

[[files]]
file = "mods/alloy-forgery.toml"
hash = "28f3a330db6ec489843622d1c0eeb6a40a92f2892073934e8ed3f974276f3519"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "068ec29e5c2383192c89411a3c47909a06f3aa1015c73cfdba1d265283196510"
metafile = true

[[files]]
file = "mods/antighost.toml"
hash = "567dea83368027d9051051a50e777ef5650f9b5ae74d8a8c5cf1fb5abb74c6d5"
metafile = true

[[files]]
file = "mods/aphid_additions.pw.toml"
hash = "f020eeecf13374d31f606707aad8e11a746081cdcb6e4baa1e9f7d9b968d5298"
metafile = true

[[files]]
file = "mods/arcanus.toml"
hash = "57e638d3a03d936fbb11cb5878292b3cc809b33351abd631a3fbe999ee8c5dea"
metafile = true

[[files]]
file = "mods/architectury-api.toml"
hash = "1ec5c09edc8d27af569ef4e087f1e74cf175e43de0172316a1fffd28290d1bd9"
metafile = true

[[files]]
file = "mods/badpackets.toml"
hash = "d8fe226cd050b8c94fcb98819b2646a74863ad8d52fc22db37c29fe66e53996d"
metafile = true

[[files]]
file = "mods/basic-shields-fabric.toml"
hash = "8979c102241e3de5365b478762d1600ca6fb5249775e6c9fa3519e0b2045830d"
metafile = true

[[files]]
file = "mods/beebuddy.pw.toml"
hash = "78eb1ea1b060a0456045f71489c2fd310350d9524e3594d0d33c09f06129df04"
metafile = true

[[files]]
file = "mods/better-mount-hud.toml"
hash = "757207131774e618e46c6c0ad407c8ba7c45d3c9c4fb59ffa8209d1bfe04a0d8"
metafile = true

[[files]]
file = "mods/blossom.toml"
hash = "f3b6e06b6315b19169e4bc81a95e68940248f7b111f0d01f638ea2be9c2da46d"
metafile = true

[[files]]
file = "mods/bobby.toml"
hash = "4491272cf1fb2adb67386c5432b4358197dc1516981460d8e0dcae972b9fe437"
metafile = true

[[files]]
file = "mods/borderless-mining.toml"
hash = "bed51582473ebbd8dc843f53f255d01a52683fa1ecd710e59eabf6173a9bdc98"
metafile = true

[[files]]
file = "mods/bosses-of-mass-destruction.toml"
hash = "8abe66f024c57efabee15007de7b70510283223dc9c4e6d0f3ef02c8d462e6b7"
metafile = true

[[files]]
file = "mods/campanion.toml"
hash = "8d3de765ffa83b0499e328dbd1827e35c2a9f88c11cdc09ba1f4efe7d68f531f"
metafile = true

[[files]]
file = "mods/capes.toml"
hash = "f726e4e0b1481c9fcebabb78da8c50382ee7add661b38f820fb5b6ab6f5c0d0b"
metafile = true

[[files]]
file = "mods/cardinal-components-api.toml"
hash = "9f6f8ef253da3c5d17050b6a5022693ed1b43f714f6f37bc5d4caf1456338f93"
metafile = true

[[files]]
file = "mods/chunky.toml"
hash = "28bb1d5f48456c9c78599e37c8c52e2a87fd30ef90bb7fcb1db24a6abd40d697"
metafile = true

[[files]]
file = "mods/continuity.toml"
hash = "4932ddd020065b82614ddb7db60679f4c615b4c780dcac10c6ca43c3ba530c62"
metafile = true

[[files]]
file = "mods/cosmetic-armor.toml"
hash = "d89f39ca5e29d9d5457c1ab65eb31fba2349bccc03a33c57823dec5823a18904"
metafile = true

[[files]]
file = "mods/create-fabric.toml"
hash = "b8eeaa92aa2dd065415afd6c449f8c785d387a9f27fc5d6e40e35c31ac6616b0"
metafile = true

[[files]]
file = "mods/createplus.toml"
hash = "84a26eada70c919e518bdc9f51f1df2b5283d98b6b1acd1d0ae33f162b5e26df"
metafile = true

[[files]]
file = "mods/culinaire.toml"
hash = "2729c49a56c9b94101d7baeb853945ae660cc1e6691abc6c402eef283901286c"
metafile = true

[[files]]
file = "mods/cull-less-leaves.toml"
hash = "cd41e5b7c8618ab49ce53eb61df2877be283b16eebf92b11f1b110bcd8494a02"
metafile = true

[[files]]
file = "mods/custom-splash-screen.toml"
hash = "23e3c4cb4e2ee0ed4cd1d9a8e1960578cf3e49839813c7930c4809aba304a1f7"
metafile = true

[[files]]
file = "mods/dawn.toml"
hash = "4319357e42e227de4a456c77953609e2e32cc2cd6558777a441b586c0cfe4839"
metafile = true

[[files]]
file = "mods/dcch.toml"
hash = "f811170d884fbbe2ccbd8e5c42137eb490d0116255878f5b53336efafcb2877c"
metafile = true

[[files]]
file = "mods/debugify.toml"
hash = "9d5d339c329cb7e2a8c7540da5dff5e81cb99b769986c3f88fcfa17d21477f18"
metafile = true

[[files]]
file = "mods/desired-servers.pw.toml"
hash = "282f0da3fba7fb5b7d53e06dcfe2b7200f118f29a48392ce497a03ecc7e8e2cb"
metafile = true

[[files]]
file = "mods/disenchanter.toml"
hash = "8f100e5959aaeb745edb9f27e5a4d6d858e530480c79c1befe3c1ff49ebe05e2"
metafile = true

[[files]]
file = "mods/dynamic-fps.toml"
hash = "ffc1f6d147394bfeb65b2fb9a78ca7d3365cbf5192c31af1312bc899190e4e34"
metafile = true

[[files]]
file = "mods/earth2java.toml"
hash = "82e315b100b9ce182fc67e7b0a2bdde3f6807efbf5b33e4970f2c6abc3bbcf61"
metafile = true

[[files]]
file = "mods/earthbounds.toml"
hash = "6829262aef70acab50c413eb88880e9679d3a6eb8e96af468f6b0718fd8583bb"
metafile = true

[[files]]
file = "mods/ebe.toml"
hash = "50780c17b5bb008c6786a9ab8e4405fba1908a8276a1d7d03dff90f8f7408d78"
metafile = true

[[files]]
file = "mods/expanded-caves.pw.toml"
hash = "d218f8b9ae54fa5b5305c7e1afe323c96b532b93fa8c9e3edae7aad10f8830d2"
metafile = true

[[files]]
file = "mods/fabric-api.toml"
hash = "736583b1e65ea2d82385279e785ed5ffe0bb52387c6c624d9b61d6366c4ccbc5"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.toml"
hash = "738ffde3eab8e9d0c616e419862ff9c588bbd6009fad70953bd4d4697c88f202"
metafile = true

[[files]]
file = "mods/fabricshieldlib.toml"
hash = "3fa20c7a4f4b3ed95d5959a2864a8a2b269e26cb33884c1acc297d72acbc2fca"
metafile = true

[[files]]
file = "mods/feature-nbt-deadlock-be-gone.toml"
hash = "eeeb1b93d454b1bebe407c191c1fd90eacf82456bf41585ca90d8fc5c4e84653"
metafile = true

[[files]]
file = "mods/ferrite-core.toml"
hash = "f19e328fe42f91d1b65e244ee5bcf70f1e5305a27278945098ea85af82e05d0d"
metafile = true

[[files]]
file = "mods/fish-of-thieves.pw.toml"
hash = "ad97511f5bd0b95146a47beb412ea482ed4941d6b3411842a166da8709ba6e16"
metafile = true

[[files]]
file = "mods/flowery-structures.toml"
hash = "3445abf5320ce5590e8ff33b030502af8100ba8d1ea94aa9f37216291621ba9a"
metafile = true

[[files]]
file = "mods/flowerycore.toml"
hash = "6956e579b5b4be69e89b8dd2818ef10beb4df9d214a52df06c114683030b6e88"
metafile = true

[[files]]
file = "mods/fowerypro.toml"
hash = "dd8bdf6455648424be1a2f192c41eaac4d63893224683ce079aa750419cdf951"
metafile = true

[[files]]
file = "mods/friends-and-foes.toml"
hash = "d3353d8bc14ca27ecb6918f4c56de094dbc46f9b407ecc97d23a2302ad5e9a31"
metafile = true

[[files]]
file = "mods/fwaystones.toml"
hash = "c69cafa2a1579de40fa2b7c4dc278bd59ab26f3e2ea79a6e1ee26d7dcd4b2b78"
metafile = true

[[files]]
file = "mods/geckolib.toml"
hash = "dd86dde9b75daf2f1c9f0e87186f5c8e728ca84dafd0986225afc25bad4aa880"
metafile = true

[[files]]
file = "mods/goml-reserved.toml"
hash = "d15760f67ce06f4f75c8c14f20cb188ea2a3601df5c1cb10e64f2c014028cc30"
metafile = true

[[files]]
file = "mods/guarding.toml"
hash = "93045a2a147e70ae59f00696531fe9ee384aaba88f5239a7b4752e9b5dcb2319"
metafile = true

[[files]]
file = "mods/guild.toml"
hash = "b4745e1dcd7e3869a0047dfcb78eb8cd7d5b528bfb97e544aecfe251cb51f2bc"
metafile = true

[[files]]
file = "mods/here-be-no-dragons.toml"
hash = "b521cb1efedc7ce0443e6df6ea00c10beb0000c769f36812840ba83abc7aa520"
metafile = true

[[files]]
file = "mods/horsebuff.toml"
hash = "8e64e605cb87282d854c4cbc974ff166f3bcd4f989c6eaa511cfa3a82f49d4fc"
metafile = true

[[files]]
file = "mods/horseinboat.toml"
hash = "cab55b9d6a2888c9de60ffe4e425c2f0fe0333e2b7806f0f3bbc8e05e9068d4b"
metafile = true

[[files]]
file = "mods/i-know-what-im-doing.toml"
hash = "d77d0fe2df4d0c37048b0cf0dbaf9ff2a5a3d1d15a3d48c61bee8e8c9e797d9e"
metafile = true

[[files]]
file = "mods/icy-incitement.toml"
hash = "473efcd8f932c19de373116114f8ce9f84bacb987991989d7e841642d253daae"
metafile = true

[[files]]
file = "mods/illager-expansion-forked.pw.toml"
hash = "0d375fd5db6f819b2203cf130e1c70f097e618e6f3abf9e9412acde281455357"
metafile = true

[[files]]
file = "mods/indium.toml"
hash = "735bb894e8fd0430de8fe331347ff24c5c64643bc65f2c040f7a82fb17e8b826"
metafile = true

[[files]]
file = "mods/iris.toml"
hash = "cbc3d6649757c3751ac73aed8df427b3ebc5685a808935b0e631d213bf6a760b"
metafile = true

[[files]]
file = "mods/kiln.toml"
hash = "2bd4443325ef2df10ef19de54454c29e15176a875ec361220762ba3bdbc81112"
metafile = true

[[files]]
file = "mods/krypton.toml"
hash = "219d4425679c60fd2855a6a39a6fccb6db3948dcc57b9da7c20907c855c5bd3d"
metafile = true

[[files]]
file = "mods/lambdabettergrass.toml"
hash = "01f79a7fb966690009a42f285e779bac8f7958df56240494e4d3d7d862332c2d"
metafile = true

[[files]]
file = "mods/lambdynamiclights.toml"
hash = "158c40f09b2ed4fe14f5f2925751796fe11f6baee7e1ac7f35931ad831631a3d"
metafile = true

[[files]]
file = "mods/language-reload.toml"
hash = "2c410266c2e5763c5ebaaedbe68519920e857c8d6edac44aadefa2b407d016f5"
metafile = true

[[files]]
file = "mods/lazydfu.toml"
hash = "ea127e8f74006f3a9ce099f9e96adaa3b3f4f281231ece703c4e7f9732137ebd"
metafile = true

[[files]]
file = "mods/lithium.toml"
hash = "83541b1d3e1e936638a6938eb505bf0f508c13aed7f8416af8d064ffc7cda4dc"
metafile = true

[[files]]
file = "mods/lovely_snails.toml"
hash = "cea7e57f790cde53db4a76005bca2079df37fcb43df16961fbc6b2e116100b9c"
metafile = true

[[files]]
file = "mods/midnightcontrols.toml"
hash = "730e22c082738967bd84bed469b3c30c89013e17d22967272adaa81ea2c6adaf"
metafile = true

[[files]]
file = "mods/minimotd.toml"
hash = "fe86d01993ca7aa4c868fa3ccaaae882753f868909711f4ddabb44a0036aa8c0"
metafile = true

[[files]]
file = "mods/mo-structures.toml"
hash = "2d28482058d2d26425ce201ff66684944cbf3bac2841cf4fbc9157fe51830fbe"
metafile = true

[[files]]
file = "mods/modmenu.toml"
hash = "8f501b0b0f968e3b4819219c5fd5c656500bb0a2736cafff092ce7279fe85574"
metafile = true

[[files]]
file = "mods/morechathistory.toml"
hash = "3da1c6f350407d59ac89fdaf76f28b53b96ab40267edd3f750d9f4c482327d5d"
metafile = true

[[files]]
file = "mods/mouse-tweaks.toml"
hash = "6ab676edd2b86bbee15552ca556304ef04916001445336dad1c249f9a3d63bfb"
metafile = true

[[files]]
file = "mods/mythicmetals.toml"
hash = "293d4b2454e8a8a8a1f108cbfbc53ad04f90bc6fcfc2c0ce3df62c7aad88eac8"
metafile = true

[[files]]
file = "mods/norecipebook-fabric.toml"
hash = "d311731f3bdaa3be7652355d22e9b61934e70764dbe73194075badcaf727e921"
metafile = true

[[files]]
file = "mods/owo-lib.toml"
hash = "8c752fa462607344229492d00c45ccd51a209f9338562e2d95b84d88d5cbcf1f"
metafile = true

[[files]]
file = "mods/paradise-lost.toml"
hash = "53d666e5ab53bc32b1785323486c8513dc0ea9bcae7aec1de686232f6dc02dc4"
metafile = true

[[files]]
file = "mods/patchouli.toml"
hash = "41648c2dd451dda685897dfe215a9d47c91ff5c62de2055ab6140ffc9cb45b45"
metafile = true

[[files]]
file = "mods/plushie.toml"
hash = "6974e3d3b42a84f3723fc3b65af43bb3bf93c900051a1f91c22c3c143c1fc684"
metafile = true

[[files]]
file = "mods/presence-footsteps.toml"
hash = "525252bb860d002a1985a4ffbb4cee19d727dc01bc78eaee0d3881e7bfff2eca"
metafile = true

[[files]]
file = "mods/projectsavethepets.pw.toml"
hash = "070b99c11a57885dd39c1064c1ea4a1d7654ee47c2f6b304d1d506f562033cc5"
metafile = true

[[files]]
file = "mods/promenade.toml"
hash = "aa63b6bd117897eb7d2fdcdae81e4bf7e426e9dd723ea06cd87cd79a39e34bda"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.toml"
hash = "d935b491016306e60b08bc234cc978ac84412d84d1ae5a9b6f8878a09ea25202"
metafile = true

[[files]]
file = "mods/repurposed-structures-fabric.toml"
hash = "4a49361d671362f6561f7c38e49adef060c38a2506ef68006cc0b6bc7b11a5d7"
metafile = true

[[files]]
file = "mods/servercore.toml"
hash = "c04e7a759cc12522f665a33cadf0fd8f182d1918ea17b7e818fee7575fca9cef"
metafile = true

[[files]]
file = "mods/shards.toml"
hash = "6d284a273a0e837276f5af1fe2e81439f956220f89efb61a4e57c9a8bac2d831"
metafile = true

[[files]]
file = "mods/snowpig-fabric.toml"
hash = "75ec3aa60f0ae0fa192a41dbc532c52ce7e345694040881a149cae3ef06fde5b"
metafile = true

[[files]]
file = "mods/sodium-extra.toml"
hash = "9f50922d190120ef3f832a8a3c6bdd123a80b9b16559a58e1b5c5a1520d9b2c4"
metafile = true

[[files]]
file = "mods/sodium.toml"
hash = "d1480fd38a1ac53311baa2d57b92556834372f6ac04c355169441df9a59a161c"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2140367d53fc14e3223ffed3802bd3a0c6548208458e0dd4aecd040d8b04cf4e"
metafile = true

[[files]]
file = "mods/starlight.toml"
hash = "722031c0ae5d2de71783d6c4bfbf1c5cd25c65e55cb42d8bb4f7cadf478c4368"
metafile = true

[[files]]
file = "mods/things.toml"
hash = "2b30f1388f00f7639796be1fe81ea3ace431785d6f0247a88671bc7e4e4afee5"
metafile = true

[[files]]
file = "mods/towers-of-the-wild-additions.toml"
hash = "ab69426b7e810d0b1812aaaf886ee2034cc8e4dd1b5f8cb000166cdbe54d6cc1"
metafile = true

[[files]]
file = "mods/trinkets.toml"
hash = "49f5590e6160266691eaca6948b33a3a2763e590ed4bcf90189f13650066c84e"
metafile = true

[[files]]
file = "mods/twigs.toml"
hash = "44f75bcda587cd98b95f19dc02abdc69a6153310afd5c06a3cc75bf1b3b9ca06"
metafile = true

[[files]]
file = "mods/universal_ores.toml"
hash = "47c2cbbd078ba86f70ea4e79b9519936aa29694ffb91d24661d9e9e88dba696f"
metafile = true

[[files]]
file = "mods/villager-hats.toml"
hash = "597bca85ce7c67ac4c3224c7d182432986260ad245247eb2896e5082b6b29985"
metafile = true

[[files]]
file = "mods/visuality.toml"
hash = "c47c339948a3dff50f1b879d6748e949c85e1a79c094aa639886b76c5b7301c8"
metafile = true

[[files]]
file = "mods/wthit.toml"
hash = "0f51270c426ece64c5436d39cf1a17fba5a58de32e4de175929acdd21edc7bc6"
metafile = true

[[files]]
file = "mods/yosbr-0.1.1.jar"
hash = "797b4096ccf2b22a76a28471836a178316042a2f490faea02ab25b75edd5c77a"

[[files]]
file = "packwiz-installer-bootstrap.jar"
hash = "a8fbb24dc604278e97f4688e82d3d91a318b98efc08d5dbfcbcbcab6443d116c"
