name: Build Modpack
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Download Dependencys
        run: |
          sudo apt install git p7zip make

      - name: Set up Go 1.18
        uses: actions/setup-go@v3
        with:
          go-version: '1.18'

      - name: Setup packwiz
        run: |
          go install github.com/packwiz/packwiz@latest
          export PATH=${PATH}:`go env GOPATH`/bin

      - name: Make Modrinth
        run: |
          make modrinth
          7z x ./build/modpack-modrinth.mrpack -o./build/.modrinth

      - name: Make PolyMC (Auto Update)
        run: |
          make polymc
          7z x ./build/modpack-polymc.zip -o./build/.polymc

      - name: Make Server (Auto Update)
        run: |
          make server
          7z x ./build/modpack-server.zip -o./build/.server

      - name: Upload Modrinth
        uses: actions/upload-artifact@v3
        with:
          name: HexMC Modrinth
          path: build/.modrinth
          
      - name: Upload PolyMC (Auto Update)
        uses: actions/upload-artifact@v3
        with:
          name: HexMC MultiMC-PolyMC Auto Update
          path: build/.polymc

      - name: Upload Server (Auto Update)
        uses: actions/upload-artifact@v3
        with:
          name: Auto Update Server
          path: build/.server
